### PR TITLE
WIP: Add groups membership to GSuite OIDC

### LINKED ISSUE #83: Support for group claims in GSuite
Hi,

This plugin allows mapping group claims to multiple Vault policies. However, the GSuite OIDC flow does not provide a `groups` claim when requested.

The configuration does not list a `groups` claim, nor is it an available scope on https://developers.google.com/identity/protocols/OpenIDConnect .

By trying around, you can discover a hidden scope https://www.googleapis.com/auth/userinfo.groups but nothing appears on the `/userinfo` endpoint when given access.

Other applications seem to fetch groups through the google API instead, with a service account impersonating a GSuite admin:
- Spinnaker https://www.spinnaker.io/setup/security/authorization/google-groups/
- Teleport https://github.com/gravitational/teleport/pull/2456 https://github.com/gravitational/teleport/pull/3122/files

Is it possible to consider adding support for GSuite OIDC, or should it be separated into another Vault plugin? If so, I can try to provide an initial implementation.

Thanks,

### PR DESCRIPTION
**Pull request by adongy**
Hi,

Since https://github.com/hashicorp/vault-plugin-auth-jwt/pull/78 is also trying to add provider-specific code, I'm submitting the GSuite version of it to start the discussion.

Closes #83 

This is very much a WIP version as it's missing tests, but it's been working for us so far.

Thanks,

### CODE REVIEW

**Comment by kalafut** [comment]
Thanks. We've had some discussions on how best to structure this, and I'll be opening a meta-issue which I'll link back to here, and to the Azure case. The main concern is how to keep the already complex configuration situation from exploding if/when there are numerous providers with their various options.

**Comment by rajith77** [comment]
Any update on when this PR will be merged and a release available?

**Comment by kalafut** [comment]
There is work in progress now to bring in this and the Azure AD groups PR.

**Comment by onetwopunch** [comment]
In case anyone comes across this before the fix is done and wants to implement it as a custom plugin but is having trouble, I've modified this PR a bit. This version allows you to just pass in a filename instead of the full JSON of the Service Account so your admin doesn't have to see the plaintext JSON, adds documentation in the README as well as an example terraform configuration to get you up an running quickly. It also moves some of the logic of group retreival to it's own package so you can easily debug permissions issues with the Admin SDK.

**[github.com/onetwopunch/vault-plugin-auth-jwt](https://github.com/onetwopunch/vault-plugin-auth-jwt)**

Diff Link: https://github.com/hashicorp/vault-plugin-auth-jwt/compare/master...onetwopunch:master?expand=1

Notable updates:
* [Instructions on setting up a client app](https://github.com/onetwopunch/vault-plugin-auth-jwt/#setting-up-client-app)
* [Terraform Sample](https://github.com/onetwopunch/vault-plugin-auth-jwt/blob/master/scripts/terraform.tf)
* [google-groups](https://github.com/onetwopunch/google-groups): Separate package including CLI for testing permissions of OAuth scopes for Admin SDK

Also something I found when integrating this into prod is that if you haven't set `disable_mlock` and you aren't running as root, you'll need to add a line like this into your startup script when you load the plugin or you'll get a very unhelpful gRPC error (took me about a day to debug):

```
/sbin/setcap cap_ipc_lock=+ep /etc/vault.d/plugins/vault-plugin-auth-jwt
```

Hope someone finds this helpful :)

**Comment by kalafut** [comment]
Thanks @onetwopunch.  #118 set up the general config for taking in this sort of extension and we've started looking at adapting this PR. We'll be sure to review your updates too.  FYI @austingebauer @tvoran

**Comment by adongy** [comment]
Hi,

Since the new PR replaces this, I'm closing it.

**Pull request closed without merging**
