### PR TITLE
Improve role config jwt bound constraint check

### PR DESCRIPTION
**Pull request by shwuandwing**
When configuring JWT roles, consider bound claims when checking if there is are bound constraints

### CODE REVIEW

**Comment by shwuandwing** [comment]
#49

**Comment by shwuandwing** [comment]
@kalafut , this is my first Github change.  Is there any more steps I have to take to get this change approved?

**Comment by kalafut** [comment]
@shwuandwing Hi. When I last looked I didn't see the CLA approval, but now that's in good shape so I'll be doing the review soon.

**Comment by kalafut** [comment]
Good catch and thanks for the submission!

**Pull request merged**
