### PR TITLE
Add OIDC provider for IBM ISAM

### PR DESCRIPTION
**Pull request by godvoigt**
# Overview

This adds a custom provider to support IBM ISAM style group claims, which are basically a space separated string of group names. It is nearly identical to the SecureAuth provider, so refactoring common code might sense.

# Design of Change
Creating a custom provider was enough to get the connection to our instance of IBM ISAM working.

# Related Issues/Pull Requests
-

# Contributor Checklist
[x] Add relevant docs to upstream Vault repository, or sufficient reasoning why docs won’t be added yet
[IBM ISAM Provider Docs PR](https://github.com/hashicorp/vault/pull/19247)
[?] Add output for any tests not ran in CI to the PR description (eg, acceptance tests)
[x] Backwards compatible

### CODE REVIEW

**Comment by austingebauer** [comment]
@godvoigt - Are you able to sign the CLA?

**Comment by godvoigt** [comment]
@austingebauer Yes I signed it, but the status here is somehow not updated. If I click on "Recheck it", I am only redirected to my Github profile.

**Comment by godvoigt** [comment]
@austingebauer The CLA is fine now :-)

**Review by austingebauer — APPROVED** [review]
Thanks, @godvoigt!

**Pull request merged**
