### PR TITLE
update deps for v0.14.2 release

### PR DESCRIPTION
**Pull request by fairclothjm**
Need to pass security scanner.

Steps:
```
go get golang.org/x/net
go get golang.org/x/text
go get golang.org/x/crypto
go get gopkg.in/yaml.v3
```

### CODE REVIEW

**Comment by calvn** [comment]
Does `go mod tidy` do anything by any chance?

**Comment by fairclothjm** [comment]
@calvn No change with go mod tidy

**Review by maxcoulombe — APPROVED** [review]
Looks good, wondering if you had the chance to run https://github.com/hashicorp/vault-plugin-auth-jwt/blob/main/tests/test.bats or any other force of automated/manual acceptance tests?

**Review by austingebauer — APPROVED** [review]

**Comment by fairclothjm** [comment]
@maxcoulombe I just ran the bats tests and all is good

```
$ ./test.bats
test.bats
 ✓ Read license
 ✓ Enable oidc auth
 ✓ Setup kv and policies
 ✓ POST /auth/oidc/config - write config
 ✓ POST /auth/oidc/role/:name - create a role
 ✓ LIST /auth/oidc/role - list roles
 ✓ GET /auth/oidc/role/:name - read a role
 ✓ DELETE /auth/oidc/role/:name - delete a role
 ✓ Login with oidc auth
 ✓ Test policy prevents kv read
 ✓ Test policy allows kv read

11 tests, 0 failures
```

I did have to modify them to pick up a local plugin binary instead of using the bundled plugin

**Pull request merged**
